# Generated by Django 2.2.6 on 2019-10-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('pub_date', models.DateField()),
                ('post', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
